- name: Prep DIR
  shell: "mkdir -pv /tmp/clickhouse-cluster/ && mkdir -pv /tmp/qryn"

- name: Prep NameSpace
  shell: "kubectl create namespace clickhouse || echo true"

- name: sync clickhouse deploy yaml
  template: src=templates/{{ item }}  dest=/tmp/{{ item }} owner=root group=root mode=0644 force=yes unsafe_writes=yes
  with_items:
    - clickhouse-cluster/clickhouse-config.yaml
    - clickhouse-cluster/clickhouse-service.yaml
    - clickhouse-cluster/clickhouse-ingress.yaml
    - clickhouse-cluster/clickhouse-user-config.yaml
    - clickhouse-cluster/clickhouse-statefulset.yml
    - qryn/qryn-deployment.yaml
    - qryn/qryn-service.yaml

- name: Setup ClickHouse Server
  shell: "cd /tmp/clickhouser-cluster && kubectl apply -f ."
  when: inventory_hostname in groups[group]

- name: Setup Qryn Server
  shell: "cd /tmp/qryn && kubectl apply -f ."
  when: inventory_hostname in groups[group]
