- name: Pre setup
  shell: "kubectl create namespace chatwithgpt || echo true; rm -f /tmp/chatwithgpt.yaml || echo true"

- name: Sync chatwithgpt deploy yaml
  template: src=templates/{{ item }}  dest=/tmp/{{ item }} owner=root group=root mode=0644 force=yes unsafe_writes=yes
  with_items:
    - chatwithgpt.yaml

- name: Setup ChatWithGPT Server
  shell: "kubectl apply -f /tmp/chatwithgpt.yaml"
  when: inventory_hostname in groups[group]
