apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-gateway
  namespace: clickhouse
spec:
  ingressClassName: nginx
  rules:
  - host: data-gateway.onwalk.net
    http:
      paths:
      - backend:
          service:
            name: qryn
            port:
              number: 3100
        path: /
        pathType: Prefix
