- name: Sync kubernetes-discovery config
  template: src=templates/kubernetes-discovery-serviceaccount.yaml dest=/tmp/ owner=root group=root mode=0644
  when: inventory_hostname in groups[group] and ( svc_discovery == 'enable' )

- name: Setup kubernetes-discovery for cluster
  shell: 'kubectl apply -f /tmp/kubernetes-discovery-serviceaccount.yaml'
  when: inventory_hostname in groups[group] and ( svc_discovery == 'enable' )

- name: Set K3S Ingress
  script: files/setup-ingress.sh {{ ingress }}  {{ ingress_ip }}
  when: inventory_hostname in groups[group] and ( ingress == 'nginx' )

- name: Sync K3S Ingress Deploy yaml
  template: src=templates/ingress-apisix-values.yaml dest=/tmp/ owner=root group=root mode=0644
  when: inventory_hostname in groups[group] and ( ingress == 'apisix' )
- name: Setup K3S Ingress
  shell: 'helm repo add apisix https://charts.apiseven.com || echo true; \
          helm repo update;                                              \
          kubectl create ns ingress || echo true;                        \
          helm upgrade --install apisix apisix/apisix --namespace ingress -f /tmp/ingress-apisix-values.yaml' 
  when: inventory_hostname in groups[group] and ( ingress == 'apisix' )

- name: Sync Apisix Ingress Dashboard yaml
  template: src=templates/ingress-apisix-dashboard.yaml dest=/tmp/ owner=root group=root mode=0644
  when: inventory_hostname in groups[group] and ( ingress == 'apisix' )
- name: Setup Apisix Ingress Dashboard
  shell: 'kubectl apply -f /tmp/ingress-apisix-dashboard.yaml'
  when: inventory_hostname in groups[group] and ( ingress == 'apisix' )

- name: Setup DNS Provider
  script: files/setup-dns-provider.sh {{ dns_ak }}  {{ dns_sk }}
  when: ( inventory_hostname in groups[group] ) and (external_dns == 'enable' )
- name: Remove DNS Provider
  shell: 'helm delete external-dns  -n external-dns'
  when: ( inventory_hostname in groups[group] ) and (external_dns == 'disable' )
  ignore_errors: yes
