- name: Set FluxCD Contoller
  script: files/setup-fluxcd.sh {{ config_repo }} {{ cluster_name }}
  when: inventory_hostname in groups[group] and ( gitops == 'enable' )

- name: Setup Prometheus Operator
  script: files/setup-prometheus-operator.sh {{ domain }}
  when: inventory_hostname in groups[group] and ( gitops == 'enable' )

- name: Setup KEDA Operator
  script: files/setup-keda-operator.sh {{ domain }}
  when: inventory_hostname in groups[group] and ( gitops == 'enable' )

- name: Set K3S Ingress
  script: files/setup-ingress.sh {{ ingress }}  {{ ingress_ip }}
  when: inventory_hostname in groups[group] and ( ingress == 'nginx' )

- name: Remove K3S ingress
  shell: 'helm delete nginx -n ingress'
  when: ( inventory_hostname in groups[group] ) and (ingress == 'disable' )
  ignore_errors: yes

- name: Sync K3S Ingress Deploy yaml
  template: src=templates/ingress-apisix-values.yaml dest=/tmp/ owner=root group=root mode=0644
  when: inventory_hostname in groups[group] and ( ingress == 'apisix' )
- name: Setup K3S Ingress
  shell: 'helm repo add apisix https://charts.apiseven.com || echo true; \
          helm repo update;                                              \
          kubectl create ns ingress || echo true;                        \
          helm upgrade --install apisix apisix/apisix --namespace ingress -f /tmp/ingress-apisix-values.yaml' 
  when: inventory_hostname in groups[group] and ( ingress == 'apisix' )

- name: Setup DNS Provider
  script: files/setup-dns-provider.sh {{ dns_ak }}  {{ dns_sk }} {{ domain }}
  when: ( inventory_hostname in groups[group] ) and (external_dns == 'enable' )

- name: Remove DNS Provider
  shell: 'helm delete external-dns  -n external-dns'
  when: ( inventory_hostname in groups[group] ) and (external_dns == 'disable' )
  ignore_errors: yes
