- name: "cluster {{ ClusterContext }} : Create namespace"
  shell: "kubectl create ns ${namespace} || echo true"
  ignore_errors: yes

- name: "cluster {{ ClusterContext }} : Clean OLD Secret"
  shell: "kubectl delete secret {{ item.secret_name }} --all -n  {{ namespace }}"
  ignore_errors: yes
  loop: "{{ generic }}"
  when: generic is defined

- name: "cluster {{ ClusterContext }} : Create New Generic secret from file"
  shell: "kubectl create secret generic {{ item.secret_name }}      \
          --from-file={{ item.secret_file }}                        \
          -n {{ namespace }}"
  loop: "{{ generic }}"
  when: generic is defined

- name: "cluster {{ ClusterContext }} : Clean OLD Secret"
  shell: "kubectl delete secret {{ item.secret_name }} -n  {{ namespace }}"
  ignore_errors: yes
  loop: "{{ secret }}"
  when: secret is defined

- name: "cluster {{ ClusterContext }} Create New Generic Secret from Key/Vaule"
  shell: 'kubectl create secret generic {{ item.secret_name }}              \
          --from-literal={{ item.sercet_key }}="{{ item.secret_value }}"    \
          -n {{ namespace }}'
  loop: "{{ secrets }}"
  when: secrets is defined

- name: "cluster {{ ClusterContext }} : Clean OLD Secret"
  shell: "kubectl delete secret {{ item.secret_name }} --all -n {{ namespace }}"
  ignore_errors: yes
  loop: "{{ tls }}"
  when: tls is defined

- name: "cluster {{ ClusterContext }} : Create New tls secret"
  shell: "kubectl create secret tls {{ item.secret_name }}                   \
          --key={{ item.keyfile }}                                    \
          --cert={{ item.certfile }}                                  \
          -n {{ namespace }}"
  loop: "{{ tls }}"
  when: tls is defined
