- name: Pre setting
  shell: "rm -f /usr/bin/promtail; mkdir -pv /etc/promtail/ && touch /var/log/positions.yaml"
  when: inventory_hostname in groups[group]

- name: Create promtail-agent config
  template: src=templates/promtail.yaml dest=/etc/promtail/promtail.yaml owner=root group=root mode=0644
  when: inventory_hostname in groups[group]

- name: Init Xtls service
  shell: 'bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @install'
  when: inventory_hostname in groups[group]

- name: Remove fluent-bit service
  shell: "systemctl disable fluent-bit && systemctl stop fluent-bit"
  when: inventory_hostname in groups[group]
