- name: Setup OpenLdap Server
  script: files/setup-openldap.sh {{ domain }} {{ secret }} {{ namespace }} {{ admin_password }}
  when: inventory_hostname in groups[group]

- name: sync ldap ingress config
  template: src=templates/{{ item }}  dest=/tmp/{{ item }} owner=root group=root mode=0644 force=yes unsafe_writes=yes
  with_items:
    - ingress.yaml

- name: Setup ldap ingress
  shell: "cd /tmp/ && kubectl apply -f ingress.yaml"
  when: inventory_hostname in groups[group]
