- name: create user prometheus
  shell: "useradd prometheus -s /sbin/nologin | echo true"
  when: inventory_hostname in groups[group]

- name: clean old file
  shell: "rm -f /usr/bin/node_exporter"
  when: inventory_hostname in groups[group]

- name: download node_exporter binary 
  shell: "curl -Lo /usr/bin/node_exporter https://mirrors.onwalk.net/tools/linux-amd64/node_exporter && chmod 755 /usr/bin/node_exporter" 
  when: inventory_hostname in groups[group]

- name: create node-exporter.service
  template: src=templates/node-exporter.service dest=/etc/systemd/system/node-exporter.service owner=root group=root mode=0644
  when: inventory_hostname in groups[group] 

- name: reload node-exporter service
  shell: 'systemctl daemon-reload'
  when: inventory_hostname in groups[group]

- name: init node-exporter service
  shell: 'systemctl restart node-exporter.service'
  when: inventory_hostname in groups[group]
