apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: httpbin-upstream
spec:
  discovery:
    type: Kubernetes
    service:
      name: httpbin-service
      namespace: default
      port: 80

---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  rules:
  - match:
      hosts:
      - httpbin.org
      http:
        paths:
        - /*
    backend:
      serviceName: httpbin-upstream
      servicePort: 80
