kind: ServiceAccount
apiVersion: v1
metadata:
 name: kubernetes-discovery
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-discovery-token
  annotations:
    kubernetes.io/service-account.name: "kubernetes-discovery"
type: kubernetes.io/service-account-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: kubernetes-discovery
rules:
- apiGroups: [""]
  resources: ["endpoints" ]
  verbs: ["get", "list", "watch" ]
- apiGroups: [""]
  resources: [ "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-discovery
subjects:
- kind: ServiceAccount
  name: kubernetes-discovery
  namespace: default
