- name: Install pkgs
  shell: 'curl -Lo /tmp/grafana-agent-0.32.1-1.amd64.deb https://mirrors.onwalk.net/pkgs/grafana-agent-0.32.1-1.amd64.deb && \
          dpkg -i /tmp/grafana-agent-0.32.1-1.amd64.deb && apt install -f'
  when: inventory_hostname in groups[group] and ansible_facts['distribution'] = "Ubuntu"
- name: Install pkgs
  shell: 'curl -Lo /tmp/grafana-agent-0.32.1-1.amd64.rpm https://mirrors.onwalk.net/pkgs/grafana-agent-0.32.1-1.amd64.rpm && \
          yum install /tmp/grafana-agent-0.32.1-1.amd64.rpm'
  when: inventory_hostname in groups[group] and ansible_facts['distribution'] != "Ubuntu"

- name: Create prometheus-agent config
  template: src=templates/prometheus.yml dest=/etc/prometheus/prometheus.yml owner=oot group=root mode=0644
  when: inventory_hostname in groups[group]

- name: Init grafana-agent service
  shell: "systemctl enable grafana-agent && systemctl daemon-reload && systemctl restart grafana-agent"
  when: inventory_hostname in groups[group]
