apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: chatgpt
    meta.helm.sh/release-namespace: chatgpt
  labels:
    app.kubernetes.io/name: chargpt
    app.kubernetes.io/version: 0.2.0
    app.kubernetes.io/instance: chatgpt
  name: chatgpt
  namespace: chatgpt
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: chatgpt
    app.kubernetes.io/instance: chatgpt
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: chatgpt
    app.kubernetes.io/name: chatgpt
  name: chatgpt
  namespace: chatgpt
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: chatgpt
      app.kubernetes.io/instance: chatgpt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mirrors
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: chatgpt
    app.kubernetes.io/name: chatgpt
  name: chatgpt
  namespace: chatgpt
spec:
  ingressClassName: nginx
  rules:
  - host: chatgpt.onwalk.net
    http:
      paths:
      - backend:
          service:
            name: chatgpt
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - chatgpt.onwalk.net
    secretName: chatgpt-tls
