name: Pulumi

on:
  push:
    branches:
      - main

jobs:
  pulumi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.0.1

    - name: Pulumi Preview
      uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: my-stack
        work-dir: cloud_manager
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

    - name: Pulumi Up
      uses: pulumi/actions@v3
      with:
        command: up
        stack-name: my-stack
        work-dir: cloud_manager
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
