- name: Pre setting
  shell: "rm -f /usr/bin/prometheus; mkdir -pv /etc/prometheus/; mkdir -pv /opt/prometheus/data-agent/ && chown prometheus:prometheus /opt/prometheus/data-agent/"
  when: inventory_hostname in groups[group]

- name: Download prometheus binary
  shell: 'curl -Lo /usr/bin/prometheus https://mirrors.onwalk.net/tools/linux-amd64/prometheus && chmod 755 /usr/bin/prometheus' 
  when: inventory_hostname in groups[group]

- name: Create prometheus-agent service
  template: src=templates/prometheus-agent.service dest=/etc/systemd/system/prometheus-agent.service owner=root group=root mode=0644
  when: inventory_hostname in groups[group] 

- name: Create prometheus-agent config
  template: src=templates/prometheus.yml dest=/etc/prometheus/prometheus.yml owner=root group=root mode=0644
  when: inventory_hostname in groups[group] 

- name: Create prometheus-agent start script
  template: src=templates/start-prometheus-agent-service.sh dest=/usr/bin/start-prometheus-agent-service.sh owner=root group=root mode=0755
  when: inventory_hostname in groups[group] 

- name: Create prometheus-agent stop script
  template: src=templates/stop-prometheus-agent-service.sh dest=/usr/bin/stop-prometheus-agent-service.sh owner=root group=root mode=0755
  when: inventory_hostname in groups[group] 

- name: Init prometheus-agent service
  shell: "systemctl enable prometheus-agent && systemctl daemon-reload && systemctl restart prometheus-agent"
  when: inventory_hostname in groups[group]

