- name: Install pkgs
  shell: 'curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh'
  when: inventory_hostname in groups[group]

- name: Create fluent-bit config
  template: src=templates/fluent-bit.conf dest=/etc/fluent-bit/fluent-bit.conf owner=root group=root mode=0644
  when: inventory_hostname in groups[group]

- name: Init fluent-bit service
  shell: "systemctl enable fluent-bit && systemctl daemon-reload && systemctl restart fluent-bit"
  when: inventory_hostname in groups[group]
