- name: Pre setting
  shell: "rm -f /usr/bin/deepflow-agent; rm -f /tmp/deepflow-agent.tar.gz"
  when: inventory_hostname in groups[group]

- name: Download prometheus binary
  shell: 'curl -Lo /tmp/deepflow-agent.tar.gz https://deepflow-ce.oss-cn-beijing.aliyuncs.com/bin/agent/stable/linux/amd64/deepflow-agent.tar.gz && \
          tar -zxvf /tmp/deepflow-agent.tar.gz -C /usr/sbin/'
  when: inventory_hostname in groups[group]

- name: Create deepflow-agent service
  template: src=templates/deepflow-agent.service dest=/etc/systemd/system/deepflow-agent.service owner=root group=root mode=0644
  when: inventory_hostname in groups[group]

- name: Create prometheus-agent config
  template: src=templates/deepflow-agent.yaml dest=/etc/deepflow-agent.yaml owner=root group=root mode=0644
  when: inventory_hostname in groups[group]

- name: Init prometheus-agent service
  shell: "systemctl enable deepflow-agent && systemctl daemon-reload && systemctl restart deepflow-agent"
  when: inventory_hostname in groups[group]
