apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: chatwithgpt
    meta.helm.sh/release-namespace: chatwithgpt
  labels:
    app.kubernetes.io/name: chargpt
    app.kubernetes.io/version: 0.2.0
    app.kubernetes.io/instance: chatwithgpt
  name: chatwithgpt
  namespace: chatwithgpt
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: chatwithgpt
    app.kubernetes.io/instance: chatwithgpt
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: chatwithgpt
    app.kubernetes.io/name: chatwithgpt
  name: chatwithgpt
  namespace: chatwithgpt
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: chatwithgpt
      app.kubernetes.io/instance: chatwithgpt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: chatwithgpt
        app.kubernetes.io/instance: chatwithgpt
    spec:
      containers:
      - name: chatwithgpt
        image: artifact.onwalk.net/public/chatwithgpt:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3000"
        - name: WEBAPP_PORT
          value: "3000"
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: chatwithgpt
    app.kubernetes.io/instance: chatwithgpt
  name: chatwithgpt
  namespace: chatwithgpt
spec:
  ingressClassName: nginx
  rules:
  - host: chatwithgpt.onwalk.net
    http:
      paths:
      - backend:
          service:
            name: chatwithgpt
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - chatwithgpt.onwalk.net
    secretName: chatwithgpt-tls
