project_id: "cloudsvcworkspace"
region: "asia-northeast1"
bucket_name: "iac_status_terraform_gcp"
firewall_rules:
  - name: allow-ingress
    network: "dev"
    allow:
      - protocol: tcp
        ports: [ "22", "8022", "80", "443" ]
    source_ranges: [ "0.0.0.0/0" ]
