region: "cloudsvcworkspace"
project_id: "cloudsvcsandbox"
bucket_name: "iac_google_cloud_terraform_status"
firewall_rules:
  - name: allow-ingress
    network: "dev"
    allow:
      - protocol: tcp
        ports: [ "22", "8022", "80", "443" ]
    source_ranges: [ "0.0.0.0/0" ]
