global:
  scrape_interval: 15s
  external_labels:
    {{ label }}
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['{{ ansible_default_ipv4.address }}:9100']
remote_write:
  - url: '{{ remote_write }}'
