name: Setup Vault Server 

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/app-pipeline-vault.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  setup-vault-server:
    uses: svc-design/actions/.github/workflows/setup-vault.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'www'
      ssh_host_ip: '8.130.36.45'
      ssh_host_name: 'www'
      ssh_host_domain: 'www.onwalk.net'
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
