name: Setup Chartmuseum Server

on:
  pull_request:
    paths:
      - '.github/workflows/app-pipeline-chartmuseum.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  setup-chartmuseum-server:
    uses: svc-design/actions/.github/workflows/setup-chartmuseum-server.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'k3s-server'
      ssh_host_ip: '35.77.36.144'
      ssh_host_name: 'k3s-server'
    secrets:
      DNS_AK: ${{ secrets.DNS_AK }}
      DNS_SK: ${{ secrets.DNS_SK }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_INIT_PASSWORD }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
