name: Setup Vault Server 

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/app-pipeline-vault.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  setup-vault-server:
    uses: svc-design/actions/.github/workflows/setup-vault.yml@main
    with:
      domain: 'onwalk.net'
      cluster_name: 'monitor'
      ssh_host_ip: 'monitor'
      ssh_host_name: 'monitor'
    secrets:
      SSH_USER: ${{ secrets.HOST_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
