name: Setup Harbor Server

on:
  pull_request:
    paths:
      - '.github/workflows/app-pipeline-harbor.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  setup-harbor-server:
    uses: svc-design/actions/.github/workflows/setup-harbor-server.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'artifact'
      ssh_host_ip: '3.113.244.61'
      ssh_host_name: 'artifact'
      ssh_host_domain: 'artifact.onwalk.net'
    secrets:
      OSS_AK: ${{ secrets.OSS_AK }}
      OSS_SK: ${{ secrets.OSS_SK }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
