name: Deploy Grafana Alloy Agent 

on:
  pull_request:
    paths:
      - '.github/workflows/app-pipeline-grafana-alloy.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  setup-cn-gateway-log-agent:
    uses: svc-design/actions/.github/workflows/setup-grafana-alloy.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'cn-k3s-cluster'
      ssh_host_name: 'cn-gateway'
      ssh_host_ip: '110.42.238.110'
      loki_journal_sources: |
        - 'loki_journal_sources_vpn.yml'
        - 'loki_journal_sources_gateway.yml'
      dry-run: 'true'
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

  setup-cn-k3s-server-log-agent:
    uses: svc-design/actions/.github/workflows/setup-grafana-alloy.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'cn-k3s-cluster'
      ssh_host_name: 'cn-k3s-server'
      ssh_host_ip: '8.130.93.47'
      loki_journal_sources: |
        - 'loki_journal_sources_vpn.yml'
        - 'loki_journal_sources_k3s_server.yml'
      dry-run: 'true'
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

  setup-cn-hw-node-log-agent:
    uses: svc-design/actions/.github/workflows/setup-grafana-alloy.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'cn-k3s-cluster'
      ssh_host_name: 'cn-hw-node'
      ssh_host_ip: '139.9.139.22'
      loki_journal_sources: |
        - 'loki_journal_sources_vpn.yml'
        - 'loki_journal_sources_k3s_agent.yml'
      dry-run: 'true'
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

  setup-global-gateway-log-agent:
    uses: svc-design/actions/.github/workflows/setup-grafana-alloy.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'global-k3s-cluster'
      ssh_host_name: 'global-gateway'
      ssh_host_ip: '52.196.108.28'
      loki_journal_sources: |
        - 'loki_journal_sources_vpn.yml'
        - 'loki_journal_sources_gateway.yml'
      dry-run: 'true'
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

  setup-global-k3s-server-log-agent:
    uses: svc-design/actions/.github/workflows/setup-grafana-alloy.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'global-k3s-cluster'
      ssh_host_name: 'k3s-server'
      ssh_host_ip: '43.207.193.125'
      loki_journal_sources: |
        - 'loki_journal_sources_vpn.yml'
        - 'loki_journal_sources_k3s_server.yml'
        - 'loki_journal_sources_postgresql.yml'
      dry-run: 'true'
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
