name: Setup Harbor Server

on:
  pull_request:
    paths:
      - '.github/workflows/app-pipeline-harbor.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  setup-k3s-cluster:
    uses: svc-design/actions/.github/workflows/setup-k3s-cluster.yml@main
    with:
      domain: 'onwalk.net'
      cluster_name: 'artifact'
      ssh_host_ip: '18.181.85.35'
      ssh_host_name: 'artifact'
    secrets:
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DNS_AK: ${{ secrets.DNS_AK }}
      DNS_SK: ${{ secrets.DNS_SK }}
      VAULT_URL: ${{ secrets.VAULT_URL }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      SSH_USER: ${{ secrets.SSH_USER }}

  setup-harbor-server:
    uses: svc-design/actions/.github/workflows/setup-harbor-server.yml@main
    with:
      domain: 'onwalk.net'
      cluster_name: 'artifact'
      ssh_host_ip: '18.181.85.35'
      ssh_host_name: 'artifact'
    secrets:
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DNS_AK: ${{ secrets.DNS_AK }}
      DNS_SK: ${{ secrets.DNS_SK }}
      OSS_AK: ${{ secrets.OSS_AK }}
      OSS_SK: ${{ secrets.OSS_SK }}
      SSH_USER: ${{ secrets.SSH_USER }}
    needs:
      - setup-k3s-cluster
