name: Setup Harbor Server

on:
  pull_request:
    paths:
      - '.github/workflows/app-pipeline-harbor.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  setup-harbor-server:
    uses: svc-design/actions/.github/workflows/setup-harbor-server.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'gloabl-k3s-server'
      ssh_host_ip: '52.196.108.28'
      ssh_host_name: 'k3s-server'
      ssh_host_domain: 'gloabl-k3s-server.svc.plus'
    secrets:
      OSS_AK: ${{ secrets.OSS_AK }}
      OSS_SK: ${{ secrets.OSS_SK }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
