name: Deploy Wireguard VPN Gateway

on:
  pull_request:
    paths:
      - '.github/workflows/app-pipeline-wireguard-vpn.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy-global-vpn-gateway:
    uses: svc-design/actions/.github/workflows/setup-vpn-gateway-new.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'global-gateway'
      ssh_host_name: 'global-gateway'
      ssh_host_ip: '52.196.108.28'
      dry-run: 'true'
      vpn_gateway_config: |
        name: 'global_gateway' 
        network: '10.255.0.1/32'
        listen_port: 51820
        tunnel: wg0
        interface: eth0
        mtu: 1200
        postup_rules:
          - 'iptables -A FORWARD -i wg0 -j ACCEPT'
          - 'iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE'
          - '/usr/local/bin/udp2raw -s -l 0.0.0.0:2443 -r 52.196.108.28:51820 -k \"udp2raw\" --raw-mode faketcp -a --log-level 3 > /tmp/udp.log &'
        postdown_rules:
          - 'iptables -D FORWARD -i wg0 -j ACCEPT'
          - 'iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE'
          - 'killall udp2raw || true'
        peers:
          - name: 'global_k3s_server_db'
            allowed_ips: '10.255.0.2/32'
            persistent_keepalive: 25
          - name: 'global_k3s_server'
            allowed_ips: '10.255.0.3/32'
            persistent_keepalive: 25
          - name: 'desktop_macbook'
            allowed_ips: '10.255.0.200/32'
            persistent_keepalive: 25
          - name: 'cn_gateway'
            allowed_ips: '10.254.0.0/16, 10.255.0.0/16'
            endpoint: '127.0.0.1:51831'
            persistent_keepalive: 25
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HCP_API_URL:  ${{ secrets.HCP_API_URL }}
      HCP_CLIENT_ID:  ${{ secrets.HCP_CLIENT_ID }}
      HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
