name: argocd job
on:
  pull_request:
    branches: ["main", "stable", "release/v*"]
  workflow_dispatch:
    branches:
      - main

jobs:
  argocd-job:
    name: 
    uses: svc-design/actions/.github/workflows/workflows-call-gitops.yaml@main
    with:
      namespace: "itsm-dev"
      helmfile: "helm_releases/apps/redis"
      config_repo: "https://github.com/svc-design/gitops.git"
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
