name: MultiCluster Pipeline 

env:
  STATE: "create"   # 可以根据需要更改初始状态, 可选create，update, destroy
  CLOUD: "gcp"       # 选择云服务商, 可选: gcp, aws, ali, azure
  DNS_AK: ${{ secrets.DNS_AK }}
  DNS_SK: ${{ secrets.DNS_SK }}
  SSH_USER: ${{ secrets.HOST_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/iac-pipeline-create.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  apply-cluster-resources:
    uses: open-source-solution-design/Modern-Container-Application-Reference-Architecture/.github/workflows/use-setup-gcp-cloud.yml@main
    secrets:
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}


  setup-monitor-cluster:
    uses: open-source-solution-design/Modern-Container-Application-Reference-Architecture/.github/workflows/use-setup-k3s-cluster.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'monitor'
      ssh_host_name: 'monitor'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
    needs:
      - apply-cluster-resources

  setup-devops-cluster:
    uses: open-source-solution-design/Modern-Container-Application-Reference-Architecture/.github/workflows/use-setup-k3s-cluster.yml@main
    with:
      domain: 'svc.plus'
      cluster_name: 'devops'
      ssh_host_name: 'devops'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
    needs:
      - apply-cluster-resources

  setup-sit-cluster:
    uses: open-source-solution-design/Modern-Container-Application-Reference-Architecture/.github/workflows/use-setup-k3s-cluster.yml@main
    with:
      cluster_name: 'sit'
      ssh_host_name: 'sit'
      domain: 'svc-sit.ink'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
    needs:
      - apply-cluster-resources

  setup-uat-cluster:
    uses: open-source-solution-design/Modern-Container-Application-Reference-Architecture/.github/workflows/use-setup-k3s-cluster.yml@main
    with:
      cluster_name: 'uat'
      ssh_host_name: 'uat'
      domain: 'svc-uat.ink'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
    needs:
      - apply-cluster-resources

  setup-prod-cluster:
    uses: open-source-solution-design/Modern-Container-Application-Reference-Architecture/.github/workflows/use-setup-k3s-cluster.yml@main
    with:
      cluster_name: 'prod'
      ssh_host_name: 'prod'
      domain: 'svc.plus'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
    needs:
      - apply-cluster-resources
