name: Signal K3S Cluster Pipeline Create with IAC tools

env:
  STATE: "create"   # 可以根据需要更改初始状态, 可选create，update, destroy
  CLOUD: "gcp"       # 选择云服务商, 可选: gcp, aws, ali, azure
  DNS_AK: ${{ secrets.DNS_AK }}
  DNS_SK: ${{ secrets.DNS_SK }}
  SSH_USER: ${{ secrets.HOST_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

on:
  pull_request:
    paths:
      - '.github/workflows/iac-pipeline-signal-cluster-create.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  apply-cluster-resources:
    uses: svc-design/actions/.github/workflows/setup-gcp-cloud.yml@main
    with:
      config: 'signal-cluster-config.yaml'
    secrets:
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

  setup-k3s-cluster:
    uses: svc-design/actions/.github/workflows/setup-k3s-cluster.yml@main
    with:
      domain: 'onwalk.net'
      cluster_name: 'monitor'
      ssh_host_name: 'monitor'
    secrets:
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DNS_AK: ${{ secrets.DNS_AK }}
      DNS_SK: ${{ secrets.DNS_SK }}
      VAULT_URL: ${{ secrets.VAULT_URL }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      SSH_USER: ${{ secrets.HOST_USER }}
    needs:
      - apply-cluster-resources

#  argocd-job:
#    name:
#    uses: svc-design/actions/.github/workflows/workflows-call-gitops.yaml@main
#    with:
#      apiserver: "https://35.200.69.238:6443"
#      namespace: "itsm-dev"
#      helmfile: "helm_releases/apps/redis"
#      config_repo: "https://github.com/svc-design/gitops.git"
#    secrets:
#      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#    needs:
#      - setup-k3s-cluster
