name: Setup Chartmuseum Demo in k3s 

on:
  schedule:
    - cron: "0 0 1 */2 *"
  pull_request:
  push:
    paths:
      - '.github/workflows/setup-chartmuseum-demo.yml'
  workflow_dispatch:
    branches: [ 'main' ]

env:
  DNS_AK: ${{ secrets.DNS_AK }}
  DNS_SK: ${{ secrets.DNS_SK }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
  ADMIN_INIT_PASSWORD: ${{ secrets.ADMIN_INIT_PASSWORD }}

defaults:
  run:
    working-directory: ./playbook

jobs:
  Setup-Chartmuseum-In-K3S:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Habor in K3S
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${SSH_PRIVATE_KEY}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa

          mkdir -pv hosts/ 
          cat > hosts/inventory << EOF
          [master]
          artifact               ansible_host=18.167.129.213
          
          [all:vars]
          dns_ak=$DNS_AK
          dns_sk=$DNS_SK
          ansible_port=22
          ansible_ssh_user=ubuntu
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          admin_password=$ADMIN_INIT_PASSWORD
          EOF
          ansible-playbook -i hosts/inventory jobs/init_chartmuseum -D
