name: setup k3s cluster with existed vhost 

on:
  workflow_dispatch:
    branches: [ 'main' ]

env:
  DNS_AK: ${{ secrets.DNS_AK }}
  DNS_SK: ${{ secrets.DNS_SK }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

defaults:
  run:
    working-directory: ./playbook

jobs:
  k3s-cluster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run playbook
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False

          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${SSH_PRIVATE_KEY}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa
          
          cat > hosts/inventory << EOF
          [master]
          mochat.onwalk.net               ansible_host=43.198.94.182
          
          [all:vars]
          ansible_port=22
          ansible_ssh_user=ubuntu
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          dns_ak=$DNS_AK
          dns_sk=$DNS_SK
          ingress_ip=43.198.94.182
          k3s_public_ip=43.198.94.182
          EOF
          ansible-playbook -i hosts/inventory jobs/init_k3s_cluster -D
          #ansible-playbook -i hosts/inventory jobs/init_chatwithgpt -D
