name: setup nginx-oss with existed vhost 

on:
  schedule:
    - cron: "0 0 1 */2 *"
  workflow_dispatch:
    branches: [ 'main' ]

env:
  DNS_AK: ${{ secrets.DNS_AK }}
  DNS_SK: ${{ secrets.DNS_SK }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

defaults:
  run:
    working-directory: ./playbook

jobs:
  k3s-cluster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run playbook
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${SSH_PRIVATE_KEY}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa

          mkdir -pv hosts/ 
          cat > hosts/inventory << EOF
          [master]
          www.onwalk.net               ansible_host=8.130.36.45
          
          [all:vars]
          ansible_port=22
          ansible_ssh_user=root
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          dns_ak=$DNS_AK
          dns_sk=$DNS_SK
          ingress_ip=8.130.36.45
          EOF
          ansible-playbook -i hosts/inventory jobs/init_k3s_cluster_std -D
          ansible-playbook -i hosts/inventory jobs/init_nginx_oss -D
