name: setup observability-server with existed vhost 

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/setup-observability-server-with-existed-vhost.yml'
  workflow_dispatch:
    branches: [ 'main' ]

env:
  DNS_AK: ${{ secrets.DNS_AK }}
  DNS_SK: ${{ secrets.DNS_SK }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  GITLAB_OIDC_CLIENT_TOKEN: ${{ secrets.GITLAB_OIDC_CLIENT_TOKEN }}

defaults:
  run:
    working-directory: ./playbook

jobs:
  setup-observability-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run playbook
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${SSH_PRIVATE_KEY}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa

          mkdir -pv hosts/ 
          cat > hosts/inventory << EOF
          [master]
          k3s              ansible_host=34.85.43.134
          
          [all:vars]
          ansible_port=22
          ansible_ssh_user=root
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          dns_ak=$DNS_AK
          dns_sk=$DNS_SK
          smtp_password=$SMTP_PASSWORD
          gitlab_oidc_client_token=$GITLAB_OIDC_CLIENT_TOKEN
          EOF
          #ansible-playbook -i hosts/inventory jobs/init_observability-server -D
          ansible-playbook -i hosts/inventory jobs/init_bookinfo -D
          ansible-playbook -i hosts/inventory jobs/init_nginx_oss -D
          ansible-playbook -i hosts/inventory jobs/init_gitlab -D
  setup-agent-for-vhosts:
    runs-on: ubuntu-latest
    needs:
      - setup-observability-server

    steps:
      - uses: actions/checkout@v3

      - name: run playbook
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${SSH_PRIVATE_KEY}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa

          mkdir -pv hosts/ 
          cat > hosts/inventory << EOF
          [master]
          vhost-1              ansible_host=35.194.101.9
          vhost-2              ansible_host=34.146.42.109
          
          [all:vars]
          ansible_port=22
          ansible_ssh_user=root
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          dns_ak=$DNS_AK
          dns_sk=$DNS_SK
          EOF
          ansible-playbook -i hosts/inventory jobs/init_log_agent -D
          ansible-playbook -i hosts/inventory jobs/init_metric_agent -D
  setup-agent-for-k8s:
    runs-on: ubuntu-latest
    needs:
      - setup-observability-server

    steps:
      - uses: actions/checkout@v3

      - name: run playbook
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${SSH_PRIVATE_KEY}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa

          mkdir -pv hosts/ 
          cat > hosts/inventory << EOF
          [master]
          k3s-dev              ansible_host=34.146.25.114
          
          [all:vars]
          ansible_port=22
          ansible_ssh_user=root
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          dns_ak=$DNS_AK
          dns_sk=$DNS_SK
          ingress_ip=34.146.25.114
          EOF
          #ansible-playbook -i hosts/inventory jobs/init_k3s_cluster -D
          ansible-playbook -i hosts/inventory jobs/init_observability-agent -D
