name: Workflow Call Setup K3S Cluster
on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      ssh_host_name:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      GCP_CREDENTIALS_JSON:
        required: true

jobs:
  setup-app-cluster:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST_DOMAIN: "${{ inputs.ssh_host_name }}.${{ inputs.domain }}"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Pre Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq
          python -m pip install --upgrade pip jinja2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set GitHub Actions output variables
        id: terraform-output
        run: |
          python3 scripts/init.py && terraform init
          SSH_HOST_IP=$(terraform output | grep "${{ inputs.ssh_host_name }}" | awk -F= '{print $2}' | tr -d ' "\n')
          echo "SSH_HOST_IP=$SSH_HOST_IP" >> $GITHUB_ENV
        working-directory: iac_modules/terraform/gcp/vhost/

      - name: Update playbook hosts
        run: bash observability-platform-pre_setup.sh
        working-directory: playbook/ 

      - name: Setup K3S Cluster
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts/inventory init_k3s_cluster_with_gitops -e "cluster_name=${inputs.ssh_host_name}" -e "domain=${inputs.domain}" -D
        working-directory: playbook/ 
