name: Workflow Call Setup Vault Server
on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      ssh_host_name:
        required: true
        type: string
      ssh_host_ip:
        required: true
        type: string
    secrets:
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  init-vault-server:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ inputs.domain }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST_IP: "${{ inputs.ssh_host_ip }}"
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST_DOMAIN: "${{ inputs.ssh_host_name }}.${{ inputs.domain }}"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Pre Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible jinja2 hvac
          ansible-galaxy collection install community.hashi_vault

      - name: Update playbook hosts
        run: bash ansible_playbook_hosts_setup.sh
        working-directory: playbook/ 

      - name: Setup Observability Agent
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts/inventory init_vault_server -e "cluster_name=${{inputs.ssh_host_name}}" -e "domain=${{inputs.domain}}" -D
        working-directory: playbook/ 
